wheat_state = ['Andhra_Pradesh', 'Assam', 'Chhatisgarh', 'Delhi', 'Haryana',
       'Jharkhand', 'Karnataka', 'Kerala', 'Maharashtra', 'Odisha',
       'Punjab', 'Rajasthan','Telangana','Uttarakhand', 'Uttar_Pradesh',
       'West_Bengal']
rice_state = ['Assam', 'Delhi', 'Jammu_and_Kashmir', 'Jharkhand', 'Karnataka',
       'Kerala', 'Maharashtra', 'Manipur', 'Meghalaya', 'Odisha',
       'Punjab', 'Rajasthan', 'Tripura', 'Uttarakhand', 'Uttar_Pradesh',
       'West_Bengal']
bajra_state = ['Delhi', 'Haryana', 'Madhya_Pradesh', 'Maharashtra', 'Rajasthan',
       'Tamil_Nadu', 'Telangana', 'Uttar_Pradesh']

wheat_district_dict ={'Andhra_Pradesh': ['Visakhapatnam', 'Cuddapah', 
       'Srikakulam', 'Vijayanagaram', 'Chittor'], 
       'Assam':['Barpeta', 'Bangaigaon', 'Cachar', 'Sonitpur', 'Nagaon',
       'Dibrugarh', 'Dhubri', 'Goalpara', 'Golaghat', 'Jorhat',
       'Karimganj', 'Darrang', 'Kamrup', 'Dhemaji', 'Sibsagar',
       'Tinsukia'], 
       'Chhatisgarh': ['Durg', 'Janjgir', 'Surguja', 'Raipur', 'Kanker', 'Mahasamund',
       'Jashpur', 'Koria', 'Balod', 'Balodabazar', 'Rajnandgaon',
       'Raigarh', 'Bastar', 'Dhamtari', 'Bemetara', 'Korba', 'Bilaspur',
       'Kondagaon', 'Gariyaband', 'Sukma', 'Dantewada', 'Kabirdham',
       'Balrampur', 'Mungeli', 'Narayanpur', 'Surajpur'], 
       'Delhi': ['Delhi'],
       'Haryana': ['Hissar', 'Ambala', 'Karnal', 'Mahendragarh-Narnaul',
       'Kurukshetra', 'Jhajar', 'Faridabad', 'Panipat', 'Panchkula',
       'Bhiwani', 'Fatehabad', 'Yamuna Nagar', 'Kaithal', 'Sirsa',
       'Gurgaon', 'Sonipat', 'Palwal', 'Mewat', 'Jind', 'Rewari',
       'Rohtak'],
       'Jharkhand': ['Bokaro', 'West Singbhum', 'East Singhbhum', 'Palamu', 'Deogarh',
       'Dhanbad', 'Dumka', 'Garhwa', 'Giridih', 'Godda', 'Gumla',
       'Hazaribagh', 'Jamtara', 'Koderma', 'Latehar', 'Lohardaga',
       'Pakur', 'Ranchi', 'Sahebgang', 'Saraikela(Kharsanwa)', 'Simdega'],
      'Karnataka': ['Gulbarga', 'Dharwad', 'Hassan', 'Belgaum', 'Bidar', 'Bagalkot',
       'Bangalore', 'Kolar', 'Bellary', 'Shimoga', 'Bijapur',
       'Chamrajnagar', 'Chikmagalur', 'Chitradurga', 'Davangere', 'Gadag',
       'Koppal', 'Madikeri(Kodagu)', 'Haveri', 'Tumkur', 'Mysore',
       'Mandya', 'Karwar(Uttar Kannad)', 'Udupi', 'Raichur',
       'Mangalore(Dakshin Kannad)'],
       'Kerala': ['Alappuzha', 'Alleppey', 'Kannur', 'Kollam', 'Malappuram',
       'Kozhikode(Calicut)', 'Thiruvananthapuram'], 
       'Maharashtra': ['Yavatmal', 'Amarawati', 'Ahmednagar', 'Latur', 'Hingoli',
       'Sholapur', 'Akola', 'Jalgaon', 'Jalana', 'Wardha', 'Aurangabad',
       'Pune', 'Beed', 'Bhandara', 'Thane', 'Nagpur', 'Nanded',
       'Buldhana', 'Nashik', 'Nandurbar', 'Dhule', 'Parbhani',
       'Osmanabad', 'Vashim', 'Raigad', 'Satara', 'Mumbai', 'Sangli',
       'Kolhapur', 'Chandrapur', 'Gadchiroli', 'Gondiya'], 
       'Odisha': ['Angul', 'Nayagarh', 'Khurda', 'Balasore', 'Mayurbhanja', 'Ganjam',
       'Kalahandi', 'Sundergarh', 'Keonjhar', 'Bhadrak', 'Deogarh',
       'Sonepur', 'Jajpur', 'Jharsuguda', 'Nuapada', 'Koraput',
       'Nowarangpur', 'Bargarh', 'Gajapati', 'Rayagada', 'Sambalpur'],
       'Punjab': ['Fazilka', 'Jalandhar', 'Sangrur', 'Moga', 'Amritsar', 'Fatehgarh',
       'Ropar (Rupnagar)', 'Nawanshahr', 'Mohali', 'Mansa', 'Muktsar',
       'Barnala', 'Gurdaspur', 'Bhatinda', 'Patiala', 'Tarntaran',
       'kapurthala', 'Hoshiarpur', 'Ludhiana', 'Faridkot', 'Ferozpur',
       'Pathankot'], 
       'Rajasthan': ['Ajmer', 'Jhalawar', 'Alwar', 'Ganganagar', 'Baran', 'Chittorgarh',
       'Jaipur', 'Dausa', 'Banswara', 'Bharatpur', 'Hanumangarh',
       'Jalore', 'Bhilwara', 'Bikaner', 'Jodhpur', 'Bundi', 'Kota',
       'Jhunjunu', 'Churu', 'Nagaur', 'Tonk', 'Dholpur', 'Sikar',
       'Swai Madhopur', 'Karauli', 'Pali', 'Udaipur'],
       'Uttarakhand': ['UdhamSinghNagar', 'Dehradoon', 'Nanital', 'Haridwar',
       'Garhwal (Pauri)', 'Champawat'], 
       'Uttar_Pradesh': ['Agra', 'Jalaun (Orai)', 'Allahabad', 'Aligarh',
       'Jyotiba Phule Nagar', 'Auraiya', 'Azamgarh', 'Raebarelli',
       'Badaun', 'Bahraich', 'Ballia', 'Banda', 'Unnao', 'Barabanki',
       'Baghpat', 'Bareilly', 'Basti', 'Hamirpur', 'Kaushambi', 'Bijnor',
       'Fatehpur', 'Bulandshahar', 'Muradabad', 'Chandauli', 'Jhansi',
       'Gorakhpur', 'Deoria', 'Saharanpur', 'Mau(Maunathbhanjan)',
       'Etawah', 'Faizabad', 'Farukhabad', 'Firozabad', 'Maharajganj',
       'Ghazipur', 'Ghaziabad', 'Gonda', 'Hathras', 'Hardoi', 'Jaunpur',
       'Kanpur', 'Chitrakut', 'Etah', 'Muzaffarnagar', 'Mathura',
       'Lakhimpur', 'Lalitpur', 'Lucknow', 'Mahoba', 'Mainpuri', 'Meerut',
       'Mirzapur', 'Pillibhit', 'Pratapgarh', 'Shahjahanpur', 'Rampur',
       'Sitapur', 'Sultanpur', 'Padrauna(Kusinagar)', 'Varanasi',
       'Siddharth Nagar', 'Ambedkarnagar', 'Balrampur', 'Kannuj',
       'Gautam Budh Nagar', 'Sonbhadra', 'Bhadohi(Sant Ravi Nagar)',
       'Sant Kabir Nagar', 'Khiri (Lakhimpur)', 'Shravasti'],
       'West_Bengal':['Jalpaiguri', 'Dakshin Dinajpur', 'Bankura', 'North 24 Parganas',
       'Sounth 24 Parganas', 'Murshidabad', 'Nadia', 'Birbhum', 'Burdwan',
       'Hooghly', 'Coochbehar', 'Medinipur(E)', 'Malda', 'Medinipur(W)',
       'Uttar Dinajpur', 'Darjeeling', 'Puruliya', 'Howrah', 'Kolkata']}

wheat_market_dict = {'Andhra_Pradesh': ['Anakapally', 'Cuddapah', 'Ichapuram', 'Narsipatnam',
       'Parvathipuram', 'Proddatur',
       'R and B Guest House,RBZ,Vizianagaram', 'Tirupati',
       'Visakhapatnam'], 
       'Assam': ['Bohorihat', 'Bongiagaon', 'Cachar', 'Dhekiajuli', 'Dhing',
       'Dibrugarh', 'Gauripur', 'Goalpara', 'Golaghat', 'Howly', 'Jorhat',
       'Karimganj', 'Kharupetia', 'Lanka', 'P.O. Uparhali Guwahati',
       'Silapathar', 'Sivasagar', 'Tinsukia'], 
       'Chhatisgarh': ['Ahivara', 'Akaltara', 'Amadula', 'Ambikapur', 'Anand Nagar',
       'Antagarh', 'Arang', 'Bagbahra', 'Bageecha', 'Baikunthpur',
       'Balod', 'Balodabazar', 'Bandhabazar', 'Baradwar', 'Baramkela',
       'Basana', 'Bastar', 'Bazar Atriya', 'Belargaon', 'Bemetara',
       'Berla', 'Bhaisma', 'Bhatapara', 'Bhavarpur', 'Bilaspur', 'Bilha',
       'Boraee', 'Champa', 'Chandrapur', 'Charama', 'Chhinari', 'Devbhog',
       'Dhamdha', 'Dhamtari', 'Dhanora', 'Dharamjaygarh', 'Dondi',
       'Dondilohara', 'Dongargaon', 'Dongargarh', 'Doranpal', 'Durg',
       'Gandai', 'Gattasilli', 'Gaurella', 'Gharghoda', 'Gidam',
       'Jagdalpur', 'Jaijaipur', 'Jaspur', 'Kanker', 'Karpawand',
       'Kasdol', 'Katghora', 'Kawardha', 'Keshkal', 'Khamhariya',
       'Kharora', 'Kharsiya', 'Kheragarh', 'Kondagoan', 'Konta', 'Kota',
       'Kotba', 'Kunkuri', 'Kurud', 'Kusmee', 'Lohandiguda', 'Lormi',
       'Mahasamund', 'Manendragarh', 'Muli', 'Munguli', 'Nagari', 'Naila',
       'Narayanpur', 'Narharpur', 'Navagaon', 'Neora', 'Pandariya',
       'Patan', 'Pathalgaon', 'Pendraroad', 'Pharasgaon', 'Pipriya',
       'Pirda', 'Pithoura', 'Pratappur', 'Raigarh', 'Raipur',
       'Rajnandgaon', 'Rajpur', 'Ramanujganj', 'Ratanpur', 'Saja',
       'Sakri', 'Sambalpur', 'Sambalpur (Bemetra)', 'Sarangarh',
       'Sarayapali', 'Sargaon', 'Shakti', 'Sitapur', 'Surajpur',
       'Takhatpur', 'Tokapal', 'Vishrampur'], 
       'Delhi': ['Najafgarh', 'Narela', 'Shahdara'], 
       'Haryana': ['Adampur', 'Adampur(Agroha)', 'Ambala Cantt.', 'Ambala City',
       'Asandh', 'Ateli', 'Babain', 'Bahadurgarh', 'Ballabhgarh',
       'Bapauli', 'Barara', 'Barwala', 'Barwala(Hisar)', 'Behal', 'Beri',
       'Bhattu Kalan', 'Bhiwani', 'Bhiwani(Bawani Khera)', 'Bhuna',
       'Bilaspur', 'Ch. Dadri', 'Cheeka', 'Chhachhrauli(Khizrabad)',
       'Chhachrauli', 'Dabwali', 'Dabwali(Chautala)', 'Dhand', 'Dharsul',
       'Ding', 'Ellanabad', 'Faridabad', 'Farukh Nagar', 'Fatehabad',
       'Ganaur', 'Gharaunda', 'Gohana', 'Gurgaon', 'Hansi',
       'Hansi(Sisai)', 'Hassanpur', 'Hathin', 'Hissar', 'Hodal',
       'Iamailabad', 'Indri', 'Israna', 'Jagadhri', 'Jakhal', 'Jhajjar',
       'Jind', 'Jui', 'Jullana', 'Jundla', 'Kaithal', 'kalanwali',
       'Kalawali(Odhan)', 'Kalayat', 'Khanina', 'Kosli', 'Kunjpura',
       'Ladwa', 'Loharu', 'Loharu(Dighwa)', 'Madlauda', 'Meham',
       'Mohindergarh', 'Mullana', 'Mullana(saha)', 'Mustafabad',
       'Naneola', 'Naraingarh', 'Narnaud(Bass)', 'Narnaul', 'Narnaund',
       'Narwana', 'New Grain Market , Ambala',
       'New Grain Market , Bhiwani', 'New Grain Market , Faridabad',
       'New Grain Market , Jind', 'New Grain Market , Panchkula',
       'New Grain Market , Rohtak', 'New Grain Market , Sonipat',
       'New Grain Market(main), Karnal', 'Nigdu', 'Nilokheri', 'Nissing',
       'Pai', 'Pai(Rajaund)', 'Palwal', 'Panchkula', 'Panipat',
       'Panipat(Baharpur)', 'Pataudi', 'Pehowa', 'Pillukhera', 'Pipli',
       'Pundri', 'Punhana', 'Radaur', 'Raipur Rai', 'Rania', 'Ratia',
       'Rattia', 'Rerozepur Zhirka', 'Rewari', 'Rohtak', 'Sadhaura',
       'Safidon', 'Samalkha', 'Sampla', 'Shahabad', 'Shahzadpur', 'Sirsa',
       'Sirsa(Malekan)', 'Siwan', 'Siwani', 'Sohna', 'Sonepat',
       'Sonepat(Kharkhoda)', 'Tarori', 'Taura', 'Thanesar', 'Tohana',
       'Tosham', 'Uchana', 'Uklana', 'Yamuna Nagar'], 
       'Jharkhand': ['Bermo', 'Bokaro (Chas)', 'Chaibasa', 'Chakulia', 'Daltenganj',
       'Deoghar', 'Dhanbad', 'Dumka', 'Gadhwah', 'Giridih', 'Godda',
       'Gumla', 'Hazaribagh', 'Jamshedpur', 'Jamtara', 'Koderma',
       'Latehar', 'Lohardaga', 'Madhupur', 'Pakur', 'Pandara', 'Ramgarh',
       'Ranchi', 'Sahebganj', 'Saraikela', 'Simdega'], 
       'Karnataka': ['Alanda', 'Annigeri', 'Arasikere', 'Athani', 'Aurad', 'Badami',
       'Bagalakot', 'Bailahongal', 'Bangalore', 'Bangarpet',
       'Basava Kalayana', 'Bellary', 'Belur', 'Bhadravathi', 'Bhalki',
       'Bidar', 'Bijapur', 'Bilagi', 'Chamaraj Nagar', 'Channapatana',
       'Channarayapatna', 'Chickkaballapura', 'Chikkamagalore',
       'Chintamani', 'Chitradurga', 'Chittapur', 'Davangere', 'Dharwar',
       'Doddaballa Pur', 'Gadag', 'Gangavathi', 'Gokak', 'Gonikappal',
       'Gulbarga', 'H.B. Halli', 'Hanagal', 'Harappana Halli', 'Harihara',
       'Hassan', 'Haveri', 'Hirekerur', 'Hiriyur', 'Holenarsipura',
       'Honnali', 'Hoovinahadagali', 'Hoskote', 'Hospet',
       'Hubli (Amaragol)', 'Huliyar', 'Humanabad', 'Hungund', 'Hunsur',
       'Jamakhandi', 'K.R. Pet', 'K.R.Nagar', 'Kadur', 'Kalagategi',
       'Karwar', 'Kolar', 'Koppa', 'Koppal', 'Kottur', 'Kudchi',
       'Kundagol', 'Kundapura', 'Kunigal', 'Kustagi', 'Laxmeshwar',
       'Lingasugur', 'Maddur', 'Madhugiri', 'Madikeri', 'Malur', 'Mandya',
       'Manvi', 'Mhalingapur', 'Mundaragi', 'Mysore (Bandipalya)',
       'Nanjangud', 'Nargunda', 'Nippani', 'Pavagada', 'Piriya Pattana',
       'Raichur', 'Ramdurga', 'Ranebennur', 'Rona', 'Sagar',
       'Sakaleshpura', 'Sankeshwar', 'Savanur', 'Shahapur', 'Shiggauv',
       'Shikaripura', 'Shimoga', 'Siddapur', 'Sindagi', 'Sindagi(Hendi)',
       'Sindhanur', 'Sira', 'Sirguppa', 'Somvarpet', 'Soundati',
       'Sringeri', 'Srirangapattana', 'Sulya', 'T. Narasipura', 'Talikot',
       'Tarikere', 'Tumkur', 'Udupi', 'Yalburga'], 
       'Kerala': ['Alappuzha', 'Cherthala', 'Cherthdla', 'Dhara', 'Harippad',
       'Kannur', 'Kollam', 'Kottakkal', 'Perambra', 'Punalur',
       'Thiruvananthapuram', 'Vengeri(Kozhikode)'], 
       'Maharashtra': ['Aarni', 'Achalpur', 'Ahmednagar', 'Ahmedpur', 'Akhadabalapur',
       'Akluj', 'Akola', 'Akole', 'Akot', 'Amalner', 'Amarawati',
       'Ambad (Vadigodri)', 'Anajngaon', 'Ashti(Karanja)',
       'Aurad Shahajani', 'Aurangabad', 'Ausa', 'Balapur', 'Baramati',
       'Barshi', 'Basmat', 'Beed', 'Bhandara', 'Bhivandi', 'Bhiwapur',
       'Bhokar', 'Bhokardan', 'Bhokardan(Pimpalgaon Renu)', 'Bhusaval',
       'Buldhana(Dhad)', 'Chakur', 'Chalisgaon', 'Chandur Bazar',
       'Chandur Railway', 'Chikali', 'Chopada', 'Darwha', 'Daryapur',
       'Deoulgaon Raja', 'Devala', 'Dhadgaon', 'Dhamngaon-Railway',
       'Dharangaon', 'Dharmabad', 'Dharni', 'Dhule', 'Digras', 'Dindori',
       'Dondaicha', 'Dondaicha(Sindhkheda)', 'Dound', 'Dudhani',
       'Fulmbri', 'Gangakhed', 'Gangapur', 'Gevrai', 'Ghansawangi',
       'Hadgaon', 'Himalyatnagar', 'Hinganghat', 'Hingoli',
       'Hingoli(Kanegoan Naka)', 'Indapur', 'Indapur(Bhigwan)',
       'Indapur(Nimgaon Ketki)', 'Jalana', 'Jalgaon',
       'Jalgaon Jamod(Aasalgaon)', 'Jalgaon(Masawat)', 'Jamkhed',
       'Jawala-Bajar', 'Jintur', 'Jintur(Bori)', 'Kada', 'Kaij',
       'Kalamb(Osmanabad)', 'Kalamnuri', 'Kalmeshwar', 'Kalvan', 'Kalyan',
       'Kannad', 'Karanja', 'Karjat(Raigad)', 'Karmala', 'Katol',
       'Khamgaon', 'Kille Dharur', 'Kopargaon', 'Koregaon', 'Kurdwadi',
       'Kurdwadi(Modnimb)', 'Lakhandur', 'Lakhani', 'Lasalgaon',
       'Lasalgaon(Niphad)', 'Lasur Station', 'Latur', 'Latur(Murud)',
       'Loha', 'Lonand', 'Lonar', 'Mahagaon', 'Majalgaon', 'Malegaon',
       'Malegaon(Vashim)', 'Malkapur', 'Mandhal', 'Mangal Wedha',
       'Mangrulpeer', 'Manmad', 'Manora', 'Mantha', 'Manwat', 'Mehekar',
       'Mohol', 'Morshi', 'Motala', 'Mudkhed', 'Mumbai', 'Murim',
       'Murtizapur', 'Nagpur', 'Naigaon', 'Nanded', 'Nandgaon', 'Nandura',
       'Nandurbar', 'Nanggaon', 'Navapur', 'Ner Parasopant', 'Newasa',
       'Nilanga', 'Nira(Saswad)', 'Pachora', 'Paithan', 'Palam',
       'Palghar', 'Palthan', 'Palus', 'Pandharpur', 'Parali Vaijyanath',
       'Paranda', 'Parbhani', 'Parola', 'Partur', 'Pathardi', 'Pathari',
       'Patur', 'Pavani', 'Pulgaon', 'Pune', 'Pune(Khadiki)', 'Purna',
       'Pusad', 'Rahata', 'Rahuri', 'Rahuri(Vambori)', 'Ramtek', 'Raver',
       'Sakri', 'Samudrapur', 'Sangamner', 'Sangli', 'Sangrampur',
       'Sangrampur(Varvatbakal)', 'Satana', 'Savner', 'Selu', 'Sengoan',
       'Shahada', 'Shegaon', 'Shevgaon', 'Shevgaon(Bodhegaon)', 'Shirpur',
       'Shirur', 'Shrigonda', 'Shrirampur', 'Shrirampur(Belapur)',
       'Sillod', 'Sillod(Bharadi)', 'Sindi', 'Sindi(Selu)',
       'Sindkhed Raja', 'Sinner', 'Solapur', 'Sonpeth', 'Tadkalas',
       'Taloda', 'Tasgaon', 'Telhara', 'Tuljapur', 'Tumsar',
       'Udgir(Devanibud)', 'Ulhasnagar', 'Umared', 'Umarga', 'Umari',
       'Umarked(Danki)', 'Umarkhed', 'Vaduj', 'Vadvani', 'Vaijpur',
       'Vani', 'Varud(Rajura Bazar)', 'Vasai', 'Wardha', 'Washim',
       'Washim(Ansing)', 'Yawal', 'Yeola', 'Yeotmal', 'Akkalkot',
       'Akkalkuwa', 'Ambejaogai', 'Ashti(Jalna)', 'Barshi(Vairag)',
       'Bodwad(Varangaon)', 'Buldhana', 'Hadgaon(Tamsa)',
       'Jalgaon(Jamod)', 'Jalkot', 'Jalna(Badnapur)', 'Kada(Ashti)',
       'Karjat(Rashin)', 'Khalanpur', 'Kinwat', 'Kolhapur(Laxmipuri)',
       'Osmanabad', 'Pachora(Bhadgaon)', 'Pune(Pimpri)',
       'Rahuri(Songaon)', 'Raver(Sauda)', 'Udgir', 'Varud', 'Aatpadi',
       'Ashti', 'Babhulgaon', 'Basmat(Kurunda)', 'Chandrapur', 'Chandvad',
       'Dindori(Vani)', 'Jaysingpur', 'Kandhar', 'Nagbhid',
       'Nagpur(Hingna)', 'Nira', 'Pandhakawada', 'Parshiwani',
       'Pimpalgaon Baswant(Saykheda)', 'Rajura', 'Risod', 'Sangola',
       'Suragana', 'Vita', 'Washi(Thane Market)', 'ZariZamini', 'Aheri',
       'Alibagh', 'Armori', 'Arvi', 'Brahmpuri', 'Fruit Market',
       'Ghatanji', 'Ghoti', 'Gondpimpri', 'Islampur', 'Jawali', 'Kalamb',
       'Khed', 'Khed(Chakan)', 'Korpana', 'Mahur', 'Mukhed', 'Nasik',
       'Panvel', 'Parner', 'Ralegaon', 'Sangli(Miraj)',
       'Sangli(Phale, Bhajipura Market)', 'Satara', 'Savali',
       'Shrigonda(Gogargaon)', 'Vai', 'Varora', 'Arjuni', 'Bhor',
       'Bodwad', 'Bori Arab', 'Chamorshi', 'Dahivadi', 'Deglur',
       'Gadhinglaj', 'Gandchiroli', 'Jamner', 'Jamner(Neri)', 'Karjat',
       'Kolhapur', 'Kundalwadi', 'Malegaon(Umarane)', 'Murud', 'Narkhed',
       'Pimpalgaon', 'Roha', 'Vadgaonpeth'], 
       'Odisha': ['Angaura', 'Bahadajholla', 'Balugaon', 'Bampada', 'Baripada',
       'Bhanjanagar', 'Bhawanipatna', 'Bonai', 'Champua', 'Chandabali',
       'Deogarh', 'Dungurapalli', 'Jajpur', 'Jharsuguda', 'Junagarh',
       'Kesinga', 'Khariar Road', 'Koraput', 'Koraput(Semilguda)',
       'Nawarangpur', 'Padampur', 'Pallahara', 'Panposh', 'Parlakhemundi',
       'Rayagada', 'Sambalpur', 'Sargipali', 'Sohela', 'Talcher'],
      
      'Punjab': ['Abohar', 'Adampur', 'Ahmedgarh', 'Ajitwal', 'Ajitwal (Chogawan)',
       'Ajitwal (Dala)', 'Ajnala', 'Ajnala (Sudhar)', 'Amargarh', 'Amloh',
       'Amloh(Gobind Garh Mandi)', 'Amritsar',
       'Amritsar(Amritsar Mewa Mandi)', 'Amritsar(Chehreta)',
       'Anandpur Sahib', 'Attari', 'Badhni Kalan',
       'Badhni Kallan (Bilaspur)', 'Baghapurana', 'Balachaur', 'Banga',
       'Banga (Kataria)', 'Banur', 'Bareta', 'Bariwala', 'Barnala',
       'Bassi Pathana', 'Batala', 'Bathinda', 'Bhadaur', 'Bhadaur(Sehna)',
       'Bhadson', 'Bhagta Bhai Ka', 'Bhagta Bhai Ka (Jalal)',
       'Bhagta Bhai Ka(Kotha Guru Ka)', 'Bhawanigarh', 'Bhikhi',
       'Bhikhiwind', 'Bhikhiwind (Algo)', 'Bhikhiwind (Basarke)',
       'Bhikhiwind (Marrimegha)', 'Bhikhiwind (Sursingh)',
       'Bhikhiwind(Khalra)', 'Bhogpur', 'Bhucho', 'Bhulath',
       'Bhulath (Ibrahimaaaaval)', 'Bhulath (Nadala)', 'Bilga',
       'Bilga (Talwan )', 'Boha', 'Budalada', 'Budhlada (Phaphre Bhaike)',
       'Chabhal', 'Chanarthal', 'Cheema', 'Chogawan', 'Dakala', 'Dasuya',
       'Dera Baba Nanak', 'Dera Bassi', 'Dhanaula', 'Dhanula (Kaleke)',
       'Dharamkot', 'Dhariwal', 'Dhilwan', 'Dhuri', 'Dinanagar', 'Dirba',
       'Doraha', 'Dudhansadhan', 'F.G.Churian', 'Faridkot',
       'Faridkot (Machakikalan)', 'Fazilka', 'Fazilka (Ladhuka)',
       'Ferozepur Cantt(Jhok Harihar)', 'Ferozepur Cantt, (Sadehasham)',
       'Ferozepur Cantt.', 'Firozepur City', 'Garh Shankar',
       'Garh Shankar(Mahalpur)', 'GarhShankar (Kotfatuhi)',
       'Garhshankar(Saila Khurd)', 'Gehri', 'Gehri(Jandiala mandi)',
       'Ghanaur', 'Giddarbaha', 'Goniana', 'Goniana(Mehma Sarja)',
       'Goraya', 'Gurdaspur', 'Guru Har Sahai', 'Hathur', 'Hoshiarpur',
       'Jagraon', 'Jaitu', 'Jaitu(Bajakhana)', 'Jalalabad',
       'Jalandhar Cantt (Jamshedpur Dana Mandi)',
       'Jalandhar Cantt(Hoshiarpur Road)', 'Jalandhar Cantt.',
       'Jalandhar City', 'Jalandhar City(Faintan Ganj)',
       'Jalandhar City(Jalandhar)',
       'Jalandhar City(Kartar Pur Dana mandi)', 'Kahnuwan', 'Kalanaur',
       'Kapurthala', 'Khadur Sahib', 'Khamano', 'Khamano (Sanghol)',
       'Khanauri', 'Khanna', 'Kharar', 'Khem karan',
       'Khemkaran (Amarkot)', 'Kila Raipur', 'Kot ise Khan', 'Kotkapura',
       'Kurali', 'Lalru', 'Lehra Gaga', 'Ludhiana',
       'Ludhiana(Mandi gill Road)', 'Ludhiana(Salem Tabri)', 'Machhiwara',
       'Majitha', 'Makhu', 'Malaoud (Siar)', 'Malerkotla', 'Mallanwala',
       'Mallanwala (KhosaDalSinghwala)', 'Maloud', 'Malout',
       'Malout (Kilianwali)', 'Malout (Panniwala)', 'Mamdot',
       'Mamdot(Tibbi Khurd)', 'Mansa', 'Mansa (Bhamekalan)',
       'Mansa (Khiala kalan)', 'Mansa(Ubha Buraj Dhilwan)', 'Maur',
       'Mehal Kalan', 'Mehal Kallan (ChananWal)', 'Mehatpur', 'Mehta',
       'Moga', 'Moonak', 'Mukerian', 'Muktsar', 'Mullanpur',
       'Mullanpur Dakha (Sawadi)', 'Nabha', 'Nakodar', 'Nakodar(Sarih)',
       'Narot J Singh', 'Naushera Pannua (Dhotian)', 'Naushera Pannuan',
       'Nawan Shahar(Mandi Aur)', 'Nawan Shahar(Mandi Jadla)',
       'Nawan Shahar(MandiRaho)', 'Nawanshahar', 'Nihal Singh Wala',
       'Nihal Singh Wala (Himmatpura)', 'Nihal Singh Wala (Rautan)',
       'Noor Mehal', 'Noor Mehal(Kot Badal Khan)', 'Pathankot',
       'Pathankot (Kanwa)', 'Patiala', 'Patiala(Anaj Mandi Sanaur Road)',
       'Patiala(New Anaj Mandi)', 'Patran', 'Patran(Ghagga Mandi)',
       'Patti', 'Phagwara', 'Phillaur', 'Phillaur(Apra Mandi)', 'Quadian',
       'Raikot', 'Raikot (Nathowal)', 'Raikot (Talwandi rai)', 'Rajpura',
       'Raman', 'Rampura Phul', 'Rampuraphul(Bhai Rupan)',
       'Rampuraphul(Chowke)', 'Rampuraphul(Dhapali)',
       'Rampuraphul(Mehraj)', 'Rampuraphul(Nabha Mandi)', 'Rayya',
       'Rayya(Sathiala)', 'Ropar', 'Sadiq', 'Sahnewal', 'Samana',
       'Samana(Gajewas)', 'Samana(Kakrala)', 'Samrala', 'Sandaur',
       'Sangat', 'Sangrur', 'Sardulgarh', 'Shahkot', 'Shakot (Malsian)',
       'Sherpur', 'Sidhwan Bet', 'Sidhwan Bet (Lodhiwala)', 'Sirhind',
       'Sri Har Gobindpur', 'Sri Har Gobindpur(Harechowal)',
       'Sulargharat', 'Sultanpur', 'Sultanpur Lodhi (Tibba)', 'Sunam',
       'Talwandi Bhai', 'Talwandi Bhai(Mudki)', 'Talwandi Sabo',
       'Talwandi Sabo(Kot Fatta)', 'Talwandi Sabo(Shekhupura)',
       'Tanda Urmur', 'Tapa', 'Tapa(Sadar Bazar)', 'Tapa(Tapa Mandi)',
       'Tarantaran', 'Zira'], 
       'Rajasthan': ['Ajmer (Grain)', 'Aklera', 'Alwar', 'Anoopgarh', 'Anta', 'Atru',
       'Atru(Kawai Salpura)', 'Badrisadri', 'Bagru', 'Bandikui',
       'Bandikui(Geejgarh)', 'Banswara', 'Baran', 'Bayana', 'Beawar',
       'Begu', 'Bhadara', 'Bharatpur', 'Bharatpur(Kumer)',
       'Bhawani Mandi', 'Bhawani Mandi(Choumehla)',
       'Bhawani Mandi(Raipur)', 'Bheenmal(Ranlwada)', 'Bhilwara',
       'Bijay Nagar', 'Bijolia', 'Bikaner (Grain)', 'Bilara', 'Bundi',
       'Chaksu', 'Chechat', 'Chhabra', 'Chhabra(Chhipabadod)', 'Chirwa',
       'Chomu', 'Churu', 'Dausa', 'Deedwana', 'Deedwana(Choti Khatu)',
       'Deeg', 'DEI(Bundi)', 'Deoli', 'Dholpur', 'Fatehnagar', 'Fatehpur',
       'Gajsinghpur', 'Gangapur', 'Gangapur City',
       'Gangapurcity(Old Lal mandi)', 'Gharsana', 'Goluwala',
       'Hanumangarh', 'Hanumangarh Town', 'Hanumangarh(Urlivas)',
       'Hindoun', 'Itawa', 'Jaipur (Grain)', 'Jaipur(Bassi)',
       'Jaipur(Grain)(Chandpole)', 'Jaitaran', 'Jaitsar', 'Jhalarapatan',
       'Jhunjhunu', 'Jodhpur (Grain)(Mandor)',
       'Jodhpur(Grain)(Bhagat Ki Kothi)', 'Jodhpur(Grain)(Phalodi)',
       'Kama', 'Kapasan', 'Kekri', 'Kesarisinghpur', 'Keshoraipatan',
       'Khairthal', 'Khajuwala', 'Khanpur', 'Khedh(Bodaramev)',
       'Khedli(laxmangarh)', 'Kherli', 'Kishan Renwal(Sambhar)',
       'Kishangarh Renwal', 'Kota', 'Kotputli', 'Kuchaman City',
       'Lalgarh Jatan', 'Lalsot', 'Lalsot(Mandabari)', 'Lunkaransar',
       'Madanganj Kishanganj', 'Mahua Mandabar(Mahua)', 'Mahuwa Mandawar',
       'Malpura', 'Malpura(Todaraisingh)', 'Mandalgarh', 'Nadwai',
       'Nagar', 'Nawalgarh', 'Neem Ka Thana', 'Nimbahera', 'Niwai',
       'Nohar', 'Nokha', 'Padampur', 'Pilli Banga', 'Pratapgarh',
       'Raisingh Nagar', 'Ramaganj Mandi', 'Rani', 'Rawatsar', 'Rawla',
       'Ridmalsar', 'Sadulpur', 'Sadulshahar', 'Sanchor', 'Sangriya',
       'Sardar Shahar', 'Sawai Madhopur', 'Sikar', 'Sojat Road',
       'Sri Karanpur', 'Sri Vijayanagar', 'Sridungargarh',
       'Sriganganagar', 'Sujangarh(Churu)', 'Sumerganj', 'Sumerpur',
       'Surajgarh', 'Suratgarh', 'Tonk', 'Udaipur', 'Uniyara',
       'Vijay Nagar(Gulabpura)'],
       'Uttarakhand': ['Bazpur', 'Dehradoon', 'Gadarpur', 'Haldwani', 'Haridwar Union',
       'Jaspur(UC)', 'Kashipur', 'Khateema', 'Kicchha', 'Kotadwara',
       'Lakshar', 'Manglaur', 'Nanakmatta', 'Ramnagar', 'Rishikesh',
       'Roorkee', 'Rudrapur', 'Sitarganj', 'Tanakpur', 'Vikasnagar'], 
      'Uttar_Pradesh': ['Agra', 'Ait', 'Ajuha', 'Aligarh', 'Allahabad', 'Amroha',
       'Auraiya', 'Azamgarh', 'Bachranwa', 'Badayoun', 'Bahraich',
       'Ballia', 'Banda', 'Bangarmau', 'Barabanki', 'Baraut', 'Bareilly',
       'Basti', 'Bharuasumerpur', 'Bharwari', 'Bijnaur', 'Bindki',
       'Buland Shahr', 'Chaandpur', 'Chandausi', 'Chandoli', 'Charra',
       'Chirgaon', 'Chorichora', 'Devariya', 'Devband', 'Divai',
       'Doharighat', 'Etawah', 'Faizabad', 'Farukhabad', 'Firozabad',
       'Gadaura', 'Gangoh', 'Gazipur', 'Ghaziabad', 'Gonda', 'Gorakhpur',
       'Gurusarai', 'Haathras', 'Hapur', 'Hardoi', 'Jalaun', 'Jarar',
       'Jaunpur', 'Jayas', 'Jhansi', 'Kanpur(Grain)', 'Karvi', 'Kasganj',
       'Khair', 'Khairagarh', 'Khatauli', 'Khekda', 'Khurja', 'Konch',
       'Kopaganj', 'Kosikalan', 'Lakhimpur', 'Lalganj', 'Lalitpur',
       'Lucknow', 'Mahoba', 'Mainpuri', 'Mawana', 'Meerut', 'Mehrauni',
       'Mirzapur', 'Moth', 'Muradabad', 'Muradnagar', 'Muzzafarnagar',
       'Najibabad', 'Nautnava', 'Orai', 'Partaval', 'Pilibhit',
       'Pratapgarh', 'Pukhrayan', 'Puranpur', 'Puwaha', 'Raibareilly',
       'Rampur', 'Rampurmaniharan', 'Saharanpur', 'Samsabad', 'Sardhana',
       'Shahjahanpur', 'Shamli', 'Sikanderabad', 'Sikandraraau',
       'Sitapur', 'Siyana', 'Sultanpur', 'Tamkuhi Road', 'Tilhar',
       'Ujhani', 'Unnao', 'Varanasi(Grain)', 'Vishalpur', 'Wansi',
       'Achnera', 'Ahirora', 'Akbarpur', 'Aliganj', 'Anandnagar',
       'Anwala', 'Atarra', 'Atrauli', 'Awagarh', 'Baberu', 'Bahedi',
       'Balrampur', 'Banthara', 'Baruwasagar', 'Bhehjoi', 'Bilsi',
       'Chhibramau', 'Chhibramau(Kannuj)', 'Chitwadagaon', 'Chutmalpur',
       'Dadri', 'Dhanura', 'Dudhi', 'Etah', 'Fatehabad', 'Fatehpur Sikri',
       'Ganjdudwara', 'Ghiraur', 'Gopiganj', 'Haldaur',
       'Hargaon (Laharpur)', 'Hasanpur', 'Jagnair', 'Jahanabad',
       'Jalalabad', 'Jasra', 'Jasvantnagar', 'Kamlaganj', 'Kannauj',
       'Kayamganj', 'Khalilabad', 'Kiratpur', 'Kishunpur', 'Madhoganj',
       'Madhogarh', 'Maholi', 'Maigalganj', 'Mau(Chitrakut)', 'Maudaha',
       'Mauranipur', 'Mehmoodabad', 'Misrikh', 'Mohamadabad', 'Mohammdi',
       'Mugrabaadshahpur', 'Naanpara', 'Nagina', 'Naugarh', 'Nawabganj',
       'Paliakala', 'Panchpedwa', 'Parikshitgarh', 'Payagpur', 'Purwa',
       'Risia', 'Robertsganj', 'Sahiyapur', 'Salon', 'Sambhal', 'Sandi',
       'Sandila', 'Sehjanwa', 'Shadabad', 'Shahabad', 'Shahganj',
       'Shahpur', 'Soharatgarh', 'Tanda', 'Tikonia', 'Tulsipur', 'Tundla',
       'Utraula', 'Varanasi(F&V)', 'Varipaal', 'Vilaspur', 'Vilthararoad',
       'Viswan', 'Yusufpur', 'Achalda', 'Bharthna', 'Dibiapur',
       'Gulavati', 'Jafarganj', 'Jhijhank', 'Kadaura', 'Kalpi',
       'Karnailganj', 'Khaga', 'Mathura', 'Mihipurwa', 'Rasda', 'Rura',
       'Safdarganj', 'Shahabad(New Mandi)', 'Shikohabad', 'Sirsa',
       'Sirsaganj', 'Tanda(Rampur)', 'Anoop Shahar', 'Bewar', 'Choubepur',
       'Dhampur', 'Fatehpur', 'Jahangirabad', 'Jamanian', 'Jangipura',
       'Javer', 'Raath', 'Rudauli', 'Sikarpur', 'Sultanpurchilkana',
       'Uttaripura', 'Babrala', 'Billsadda', 'Dankaur', 'Dataganj',
       'Golagokarnath', 'Hamirpur', 'Kurara', 'Ruperdeeha', 'Saidpur',
       'Shahaswan', 'Visoli', 'Wazirganj', 'Badda', 'Barhaj',
       'Maharajganj', 'Mau', 'Muskara', 'Richha', 'Milak', 'Sindholi'],
       'West_Bengal': ['Alipurduar', 'Balurghat', 'Bankura Sadar', 'Barasat',
       'Baruipur(Canning)', 'Belacoba', 'Beldanga', 'Bethuadahari',
       'Birbhum', 'Bishnupur(Bankura)', 'Bolpur', 'Burdwan',
       'Champadanga', 'Coochbehar', 'Dinhata', 'Durgapur', 'Egra/contai',
       'English Bazar', 'Ghatal', 'Guskara', 'Habra', 'Haldibari',
       'Indus', 'Islampur', 'Jalpaiguri Sadar', 'Jangipur', 'Jhargram',
       'Kaliaganj', 'Kalimpong', 'Kalipur(Champadanga)', 'Kalna',
       'Kalyani', 'Karimpur', 'Kasimbazar', 'Katwa', 'Khatra', 'Lalbagh',
       'Mathabhanga', 'Medinipur(West)', 'Memari', 'Midnapore Sadar',
       'Nadia', 'Pandua', 'Pundibari', 'Purulia', 'Raiganj(Kalinganj)',
       'Ramkrishanpur(Howrah)', 'Rampurhat', 'Sainthia(Suri)', 'Samsi',
       'Tamluk (Medinipur E)', 'Toofanganj', 'Asansol', 'Baxirhat',
       'Chakdah', 'Darjeeling(Klimpong)', 'Diamond Harbour',
       'Falakata(Dhupguri)', 'Gajol', 'Gangarampur', 'Howrah',
       'Jiaganj(Lalbagh)', 'Kandi', 'Kolaghat', 'Mekhliganj',
       'Sealdah Koley Market', 'Sheoraphuly', 'Balarampur', 'Bishnupur',
       'ChinSurah', 'Darjeeling', 'Diamond Harbour(South 24-pgs)',
       'Falakata', 'Garbeta(Medinipur)', 'Guskara(Burdwan)',
       'Indus(Bankura Sadar)', 'Jiaganj', 'Kalipur',
       'Karsiyang(Matigara)', 'Kasipur', 'Raiganj', 'Ranaghat',
       'Ranaghat(Kalyani)', 'Sainthia', 'Siliguri', 'Uluberia',
       'Gangarampur(Dakshin Dinajpur)']}

rice_district_dict ={'Assam': ['Barpeta', 'Bangaigaon', 'Cachar', 'Sonitpur', 'Nagaon',
       'Dibrugarh', 'Dhubri', 'Goalpara', 'Golaghat', 'Kamrup',
       'Hailakandi', 'Jorhat', 'Karimganj', 'Darrang', 'Nalbari',
       'Lakhimpur', 'Dhemaji', 'Sibsagar', 'Kokrajhar', 'Tinsukia'], 
       'Delhi': ['Delhi'],
       'Jammu_and_Kashmir': ['Jammu'], 
       'Jharkhand': ['Bokaro', 'West Singbhum', 'East Singhbhum', 'Palamu', 'Deogarh',
       'Dhanbad', 'Dumka', 'Garhwa', 'Giridih', 'Godda', 'Gumla',
       'Hazaribagh', 'Jamtara', 'Ranchi', 'Koderma', 'Latehar',
       'Lohardaga', 'Pakur', 'Sahebgang', 'Saraikela(Kharsanwa)',
       'Simdega'], 
       'Karnataka': ['Dharwad', 'Hassan', 'Belgaum', 'Bangalore', 'Kolar',
       'Mangalore(Dakshin Kannad)', 'Shimoga', 'Bidar', 'Chitradurga',
       'Chamrajnagar', 'Davangere', 'Chikmagalur', 'Gulbarga', 'Koppal',
       'Madikeri(Kodagu)', 'Tumkur', 'Bellary', 'Haveri',
       'Karwar(Uttar Kannad)', 'Mysore', 'Bagalkot', 'Mandya', 'Udupi',
       'Raichur', 'Gadag', 'Bijapur'], 
       'Kerala': ['Idukki', 'Alappuzha', 'Ernakulam', 'Kollam', 'Thiruvananthapuram',
       'Alleppey', 'Kottayam', 'Kozhikode(Calicut)', 'Wayanad', 'Kannur',
       'Kasargod', 'Malappuram', 'Pathanamthitta'], 
       'Maharashtra': ['Sangli', 'Amarawati', 'Gadchiroli', 'Latur', 'Sholapur', 'Akola',
       'Ahmednagar', 'Raigad', 'Beed', 'Gondiya', 'Pune', 'Bhandara',
       'Thane', 'Nanded', 'Jalana', 'Jalgaon', 'Nashik', 'Yavatmal',
       'Dhule', 'Mumbai', 'Kolhapur', 'Parbhani', 'Chandrapur', 'Hingoli',
       'Satara', 'Vashim', 'Buldhana', 'Nagpur', 'Nandurbar', 'Ratnagiri',
       'Osmanabad', 'Aurangabad'], 
       'Manipur': ['Bishnupur', 'Imphal West', 'Imphal East', 'Chandel', 'Thoubal'], 'Meghalaya': ['South Garo Hills', 'West Garo Hills', 'West Jaintia Hills',
       'East Jaintia Hills', 'South West Khasi Hills', 'Nongpoh (R-Bhoi)',
       'East Khasi Hills'],
       'Odisha': ['Keonjhar', 'Angul', 'Bargarh', 'Nayagarh', 'Khurda', 'Balasore',
       'Cuttack', 'Mayurbhanja', 'Bhadrak', 'Ganjam', 'Kalahandi',
       'Sonepur', 'Bolangir', 'Sundergarh', 'Boudh', 'Kendrapara',
       'Deogarh', 'Dhenkanal', 'Puri', 'Rayagada', 'Jagatsinghpur',
       'Jajpur', 'Koraput', 'Jharsuguda', 'Kandhamal', 'Gajapati',
       'Nuapada', 'Malkangiri', 'Nowarangpur', 'Sambalpur'],
       'Punjab': ['Fazilka', 'Amritsar', 'Muktsar', 'Barnala', 'Fatehgarh',
       'Gurdaspur', 'Tarntaran', 'kapurthala', 'Patiala', 'Ludhiana',
       'Faridkot', 'Jalandhar', 'Mohali', 'Sangrur'], 
       'Rajasthan': ['Sirohi', 'Ajmer', 'Bhilwara', 'Bundi', 'Sikar', 'Hanumangarh',
       'Jaipur', 'Ganganagar', 'Tonk', 'Bikaner', 'Chittorgarh'],
       'Tripura': ['Khowai', 'South District', 'Sepahijala', 'West District',
       'Dhalai', 'North Tripura', 'Gomati', 'Unokoti'], 
       'Uttarakhand': ['UdhamSinghNagar', 'Dehradoon', 'Nanital', 'Haridwar',
       'Garhwal (Pauri)', 'Champawat'], 
       'Uttar_Pradesh': ['Agra', 'Jalaun (Orai)', 'Allahabad', 'Aligarh',
       'Jyotiba Phule Nagar', 'Auraiya', 'Azamgarh', 'Raebarelli',
       'Badaun', 'Bahraich', 'Ballia', 'Banda', 'Unnao', 'Barabanki',
       'Baghpat', 'Bareilly', 'Basti', 'Hamirpur', 'Kaushambi', 'Bijnor',
       'Fatehpur', 'Bulandshahar', 'Muradabad', 'Chandauli', 'Jhansi',
       'Gorakhpur', 'Deoria', 'Saharanpur', 'Mau(Maunathbhanjan)',
       'Etawah', 'Faizabad', 'Farukhabad', 'Firozabad', 'Maharajganj',
       'Ghazipur', 'Ghaziabad', 'Gonda', 'Hathras', 'Hardoi', 'Jaunpur',
       'Kanpur', 'Chitrakut', 'Etah', 'Muzaffarnagar', 'Mathura',
       'Lakhimpur', 'Lalitpur', 'Lucknow', 'Mahoba', 'Mainpuri', 'Meerut',
       'Mirzapur', 'Pillibhit', 'Pratapgarh', 'Shahjahanpur', 'Rampur',
       'Sitapur', 'Sultanpur', 'Padrauna(Kusinagar)', 'Varanasi',
       'Siddharth Nagar', 'Ambedkarnagar', 'Balrampur', 'Kannuj',
       'Gautam Budh Nagar', 'Sonbhadra', 'Bhadohi(Sant Ravi Nagar)',
       'Sant Kabir Nagar', 'Khiri (Lakhimpur)', 'Shravasti'],
       'West_Bengal':['Jalpaiguri', 'Dakshin Dinajpur', 'Bankura', 'North 24 Parganas',
       'Sounth 24 Parganas', 'Murshidabad', 'Nadia', 'Birbhum', 'Burdwan',
       'Hooghly', 'Coochbehar', 'Medinipur(E)', 'Malda', 'Medinipur(W)',
       'Uttar Dinajpur', 'Darjeeling', 'Puruliya', 'Howrah', 'Kolkata']}
       
rice_market_dict = {'Assam': ['Bohorihat', 'Bongiagaon', 'Cachar', 'Dhekiajuli', 'Dhing',
       'Dibrugarh', 'Gauripur', 'Goalpara', 'Golaghat', 'Goreswar',
       'Hailakandi', 'Howly', 'Jorhat', 'Karimganj', 'Kharupetia',
       'Lanka', 'Nalbari', 'North Lakhimpur', 'P.O. Uparhali Guwahati',
       'Silapathar', 'Sivasagar', 'Srirampur', 'Tinsukia'], 
       'Delhi': ['Najafgarh', 'Narela', 'Shahdara'],
       'Jammu_and_Kashmir': ['Jammu (Grain Mandi)'], 
       'Jharkhand': ['Bermo', 'Bokaro (Chas)', 'Chaibasa', 'Chakulia', 'Daltenganj',
       'Deoghar', 'Dhanbad', 'Dumka', 'Gadhwah', 'Giridih', 'Godda',
       'Gumla', 'Hazaribagh', 'Jamshedpur', 'Jamtara', 'Khunti',
       'Koderma', 'Latehar', 'Lohardaga', 'Madhupur', 'Pakur', 'Ramgarh',
       'Ranchi', 'Sahebganj', 'Saraikela', 'Simdega', 'Pandara'],
       'Karnataka': ['Annigeri', 'Arasikere', 'Athani', 'Bailahongal', 'Bangalore',
       'Bangarpet', 'Bantwala', 'Belthangdi', 'Belur', 'Bhadravathi',
       'Bhalki', 'Bidar', 'Challakere', 'Chamaraj Nagar', 'Channagiri',
       'Channapatana', 'Channarayapatna', 'Chickkaballapura',
       'Chikkamagalore', 'Chintamani', 'Chitradurga', 'Chittapur',
       'Davangere', 'Dharwar', 'Doddaballa Pur', 'Gangavathi',
       'Gonikappal', 'Gowribidanoor', 'Gubbi', 'Gulbarga', 'Gundlupet',
       'H.B. Halli', 'Hanagal', 'Harappana Halli', 'Harihara', 'Hassan',
       'Haveri', 'Hirekerur', 'Hiriyur', 'Holenarsipura', 'Honnali',
       'Honnavar', 'Hosadurga', 'Hospet', 'Huliyar', 'Humanabad',
       'Hunsur', 'Jamakhandi', 'K.R. Pet', 'K.R.Nagar', 'Kadur',
       'Kalagategi', 'Kanakapura', 'Karkala', 'Karwar', 'Kolar',
       'Kollegal', 'Koppa', 'Kumta', 'Kundagol', 'Kundapura', 'Kunigal',
       'Lingasugur', 'Maddur', 'Madhugiri', 'Madikeri', 'Malur', 'Mandya',
       'Mangalore', 'Manvi', 'Moodigere', 'Mulabagilu', 'Mundgod',
       'Mysore (Bandipalya)', 'Nagamangala', 'Nanjangud', 'Nippani',
       'Pandavapura', 'Pavagada', 'Piriya Pattana', 'Puttur', 'Raichur',
       'Ramanagara', 'Ranebennur', 'Rona', 'Sagar', 'Sakaleshpura',
       'Sankeshwar', 'Santhesargur', 'Sedam', 'Shahapur', 'Shikaripura',
       'Shimoga', 'Siddapur', 'Sindhanur', 'Sira', 'Sirguppa',
       'Somvarpet', 'Soundati', 'Sringeri', 'Srinivasapur',
       'Srirangapattana', 'Sulya', 'T. Narasipura', 'Tarikere', 'Tumkur',
       'Turvekere', 'Udupi', 'Yalburga', 'Yellapur', 'Arakalgud',
       'Bagepalli', 'Bellary', 'Bijapur', 'Gadag', 'Hoovinahadagali',
       'Hosanagar', 'Hoskote', 'Hubli (Amaragol)', 'Karatgi', 'Kudchi',
       'Nargunda', 'Sindagi', 'Sindagi(Hendi)', 'Sirsi', 'Thirthahalli'], 
       'Kerala': ['Adimali', 'Alappuzha', 'Aluva', 'Anchal', 'Anyara(EEC)', 'Aroor',
       'Chala', 'Chanthroor', 'Chathanoor', 'Chengannur', 'Cherthala',
       'Dhara', 'Ernakulam', 'Ettumanoor', 'Harippad', 'Kallachi',
       'Kalpetta', 'Kanjirappally', 'Kannur', 'Kasargod', 'Kayamkulam',
       'Kayamkulam(Alleppey)', 'Kollam', 'Kondotty', 'Kottakkal',
       'Kottarakkara', 'Kottayam', 'Kuruppanthura', 'Manjeri', 'Mannar',
       'Moovattupuzha', 'Munnar', 'Nedumangadu', 'Nedumkandam',
       'Neeleswaram', 'Pala', 'Parakkodu', 'Parappanangadi', 'Payyannur',
       'Perinthalmanna', 'Piravam', 'Pulpally', 'Punalur', 'Sasthamkotta',
       'Thalasserry', 'Thirurrangadi', 'Thiruvananthapuram', 'Thodupuzha',
       'Vandiperiyar', 'Vengeri(Kozhikode)'], 
       'Maharashtra': ['Aatpadi', 'Achalpur', 'Aheri', 'Ahmedpur', 'Akluj', 'Akola',
       'Akole', 'Akot', 'Alibagh', 'Amarawati', 'Ambejaogai', 'Amgaon',
       'Arjuni', 'Armori', 'Armori(Desaiganj)', 'Baramati', 'Barshi',
       'Barshi(Vairag)', 'Bhandara', 'Bhivandi', 'Bhokar', 'Bhokardan',
       'Bhor', 'Chalisgaon', 'Devala', 'Digras', 'Dindori',
       'Dondaicha(Sindhkheda)', 'Dound', 'Fruit Market', 'Gadhinglaj',
       'Gandchiroli', 'Gangakhed', 'Ghoti', 'Gondiya', 'Gondpimpri',
       'Goregaon', 'Hadgaon', 'Hingoli', 'Indapur', 'Indapur(Bhigwan)',
       'Indapur(Nimgaon Ketki)', 'Islampur', 'Jalgaon',
       'Jalgaon(Masawat)', 'Jawali', 'Jaysingpur', 'Jintur', 'Kalvan',
       'Kalyan', 'Karad', 'Karanja', 'Karjat', 'Karjat(Raigad)',
       'Khalanpur', 'Khed(Chakan)', 'Kinwat', 'Kolhapur',
       'Kolhapur(Laxmipuri)', 'Korpana', 'Kurdwadi', 'Kurdwadi(Modnimb)',
       'Lakhandur', 'Lasalgaon', 'Lasalgaon(Niphad)', 'Latur', 'Mahad',
       'Malkapur', 'Mandhal', 'Mangaon', 'Mangrulpeer', 'Mumbai', 'Murud',
       'Nagpur', 'Nagpur(Hingna)', 'Nanded', 'Nandurbar', 'Navapur',
       'Newasa', 'Nira', 'Nira(Saswad)', 'Pachora', 'Palghar', 'Palthan',
       'Pandhakawada', 'Pandharpur', 'Panvel', 'Parshiwani', 'Patan',
       'Pavani', 'Pen', 'Pune', 'Pune(Pimpri)', 'Pusad', 'Rahuri',
       'Ramtek', 'Ratnagiri (Nachane)', 'Raver', 'Roha', 'Sakri',
       'Sangamner', 'Sangli', 'Satana', 'Satara', 'Savali', 'Savner',
       'Shahada', 'Shirpur', 'Shirur', 'Shrirampur', 'Sinner', 'Solapur',
       'Suragana', 'Tiroda', 'Tuljapur', 'Tumsar', 'Ulhasnagar', 'Umared',
       'Umarga', 'Vaijpur', 'Varora', 'Vasai', 'Vita',
       'Washi(Thane Market)'], 'Manipur': ['Bishenpur', 'Imphal', 'Lamlong Bazaar', 'Moreh', 'Thoubal'], 
       'Meghalaya': ['Baghmara', 'Garobadha', 'Jowai', 'Khliehriat', 'Laskein',
       'Mawkyrwat', 'Nongpoh (R-Bhoi)', 'Rongram', 'Shillong', 'Wahiajer'], 
       'Odisha': ['Anandapur', 'Angaura', 'Angul', 'Angul(Atthamallick)',
       'Angul(Jarapada)', 'Attabira', 'Bahadajholla', 'Balugaon',
       'Bampada', 'Banki', 'Bargarh', 'Bargarh(Barapalli)', 'Barikpur',
       'Baripada', 'Betnoti', 'Bhadrak', 'Bhanjanagar', 'Bhawanipatna',
       'Birmaharajpur', 'Bolangir', 'Bolangir(Patnagarh)', 'Bonai',
       'Boudh', 'Champua', 'Chandabali', 'Chatta Krushak Bazar',
       'Deogarh', 'Dhenkanal', 'Digapahandi', 'Dumal', 'Dungurapalli',
       'Gabadkunda', 'Godabhaga', 'Gopa', 'Gunpur', 'Hindol',
       'Hinjilicut', 'Jagatsinghpur', 'Jajpur', 'Jaleswar', 'Jatni',
       'Jeypore', 'Jeypore(Kotpad)', 'Jharsuguda', 'Jhumpura', 'Junagarh',
       'Kalahandi(Dharamagarh)', 'Kandhamal', 'Kantabaji', 'Kasinagar',
       'Kendrapara', 'Kendrapara(Marshaghai)', 'Kendupatna',
       'Kendupatna(Niali)', 'Keonjhar', 'Keonjhar(Dhekikote)', 'Kesinga',
       'Khariar Road', 'Malkanagiri', 'Malkangiri(Korakunda)',
       'Mukhiguda', 'Nabarangpur(Umerkote)', 'Nawarangpur', 'Nilagiri',
       'Nimapara', 'Padampur', 'Panposh', 'Parlakhemundi',
       'Puri(Brahmagiri)', 'Rairakhol', 'Rayagada', 'Rayagada(Muniguda)',
       'Saharpada', 'Sahidngar', 'Sakhigopal', 'Sambalpur', 'Sarankul',
       'Saraskana', 'Sargipali', 'Sohela', 'Talcher', 'Tusura', 'Udala',
       'Karanjia', 'Pallahara', 'Pattamundai', 'Rahama', 'Tileibani'], 
       'Punjab': ['Abohar', 'Ajnala', 'Bariwala', 'Barnala', 'Bassi Pathana',
       'Batala', 'Bhikhiwind', 'Bhikhiwind(Khalra)', 'Dhilwan',
       'Dinanagar', 'Dudhansadhan', 'Gehri', 'Jagraon', 'Jaitu',
       'Jalalabad', 'Jalandhar City', 'Jalandhar City(Jalandhar)',
       'Kapurthala', 'Khadur Sahib', 'Khem karan', 'Khemkaran (Amarkot)',
       'Kotkapura', 'Lalru', 'Majitha', 'Malout', 'Muktsar', 'Mullanpur',
       'Patiala', 'Phagwara', 'Rajpura', 'Sadiq', 'Samana', 'Sultanpur',
       'Sunam', 'Tarantaran'], 
       'Rajasthan': ['Abu Road', 'Beawar', 'Bhilwara', 'Bijay Nagar', 'Bundi',
       'Fatehpur', 'Hanumangarh', 'Hanumangarh Town', 'Jaipur (Grain)',
       'Jaitsar', 'Niwai', 'Nokha', 'Padampur', 'Pratapgarh', 'Suratgarh'],
       'Tripura': ['Bachaibari', 'Barpathari', 'Biokhora', 'Bishalgarh',
       'Bishramganj', 'Boxonagar', 'Champaknagar', 'Chowmanu', 'Dasda',
       'Gandacharra', 'Garjee', 'Halahali', 'Jumpuijala', 'Kalsi',
       'Kalyanpur', 'Kamalghat', 'Kulai', 'Manubazar', 'Masli',
       'Melaghar', 'Mohanpur', 'Nutanbazar', 'Pabiacherra', 'Panichowki',
       'Panisagar', 'Santir Bazar', 'Silachhari', 'Sonamura', 'Teliamura'],
       'Uttarakhand': ['Bazpur', 'Dehradoon', 'Gadarpur', 'Haldwani', 'Haridwar Union',
       'Jaspur(UC)', 'Kashipur', 'Khateema', 'Kicchha', 'Kotadwara',
       'Lakshar', 'Manglaur', 'Nanakmatta', 'Ramnagar', 'Rishikesh',
       'Roorkee', 'Rudrapur', 'Sitarganj', 'Tanakpur', 'Vikasnagar'], 
      'Uttar_Pradesh': ['Agra', 'Ait', 'Ajuha', 'Aligarh', 'Allahabad', 'Amroha',
       'Auraiya', 'Azamgarh', 'Bachranwa', 'Badayoun', 'Bahraich',
       'Ballia', 'Banda', 'Bangarmau', 'Barabanki', 'Baraut', 'Bareilly',
       'Basti', 'Bharuasumerpur', 'Bharwari', 'Bijnaur', 'Bindki',
       'Buland Shahr', 'Chaandpur', 'Chandausi', 'Chandoli', 'Charra',
       'Chirgaon', 'Chorichora', 'Devariya', 'Devband', 'Divai',
       'Doharighat', 'Etawah', 'Faizabad', 'Farukhabad', 'Firozabad',
       'Gadaura', 'Gangoh', 'Gazipur', 'Ghaziabad', 'Gonda', 'Gorakhpur',
       'Gurusarai', 'Haathras', 'Hapur', 'Hardoi', 'Jalaun', 'Jarar',
       'Jaunpur', 'Jayas', 'Jhansi', 'Kanpur(Grain)', 'Karvi', 'Kasganj',
       'Khair', 'Khairagarh', 'Khatauli', 'Khekda', 'Khurja', 'Konch',
       'Kopaganj', 'Kosikalan', 'Lakhimpur', 'Lalganj', 'Lalitpur',
       'Lucknow', 'Mahoba', 'Mainpuri', 'Mawana', 'Meerut', 'Mehrauni',
       'Mirzapur', 'Moth', 'Muradabad', 'Muradnagar', 'Muzzafarnagar',
       'Najibabad', 'Nautnava', 'Orai', 'Partaval', 'Pilibhit',
       'Pratapgarh', 'Pukhrayan', 'Puranpur', 'Puwaha', 'Raibareilly',
       'Rampur', 'Rampurmaniharan', 'Saharanpur', 'Samsabad', 'Sardhana',
       'Shahjahanpur', 'Shamli', 'Sikanderabad', 'Sikandraraau',
       'Sitapur', 'Siyana', 'Sultanpur', 'Tamkuhi Road', 'Tilhar',
       'Ujhani', 'Unnao', 'Varanasi(Grain)', 'Vishalpur', 'Wansi',
       'Achnera', 'Ahirora', 'Akbarpur', 'Aliganj', 'Anandnagar',
       'Anwala', 'Atarra', 'Atrauli', 'Awagarh', 'Baberu', 'Bahedi',
       'Balrampur', 'Banthara', 'Baruwasagar', 'Bhehjoi', 'Bilsi',
       'Chhibramau', 'Chhibramau(Kannuj)', 'Chitwadagaon', 'Chutmalpur',
       'Dadri', 'Dhanura', 'Dudhi', 'Etah', 'Fatehabad', 'Fatehpur Sikri',
       'Ganjdudwara', 'Ghiraur', 'Gopiganj', 'Haldaur',
       'Hargaon (Laharpur)', 'Hasanpur', 'Jagnair', 'Jahanabad',
       'Jalalabad', 'Jasra', 'Jasvantnagar', 'Kamlaganj', 'Kannauj',
       'Kayamganj', 'Khalilabad', 'Kiratpur', 'Kishunpur', 'Madhoganj',
       'Madhogarh', 'Maholi', 'Maigalganj', 'Mau(Chitrakut)', 'Maudaha',
       'Mauranipur', 'Mehmoodabad', 'Misrikh', 'Mohamadabad', 'Mohammdi',
       'Mugrabaadshahpur', 'Naanpara', 'Nagina', 'Naugarh', 'Nawabganj',
       'Paliakala', 'Panchpedwa', 'Parikshitgarh', 'Payagpur', 'Purwa',
       'Risia', 'Robertsganj', 'Sahiyapur', 'Salon', 'Sambhal', 'Sandi',
       'Sandila', 'Sehjanwa', 'Shadabad', 'Shahabad', 'Shahganj',
       'Shahpur', 'Soharatgarh', 'Tanda', 'Tikonia', 'Tulsipur', 'Tundla',
       'Utraula', 'Varanasi(F&V)', 'Varipaal', 'Vilaspur', 'Vilthararoad',
       'Viswan', 'Yusufpur', 'Achalda', 'Bharthna', 'Dibiapur',
       'Gulavati', 'Jafarganj', 'Jhijhank', 'Kadaura', 'Kalpi',
       'Karnailganj', 'Khaga', 'Mathura', 'Mihipurwa', 'Rasda', 'Rura',
       'Safdarganj', 'Shahabad(New Mandi)', 'Shikohabad', 'Sirsa',
       'Sirsaganj', 'Tanda(Rampur)', 'Anoop Shahar', 'Bewar', 'Choubepur',
       'Dhampur', 'Fatehpur', 'Jahangirabad', 'Jamanian', 'Jangipura',
       'Javer', 'Raath', 'Rudauli', 'Sikarpur', 'Sultanpurchilkana',
       'Uttaripura', 'Babrala', 'Billsadda', 'Dankaur', 'Dataganj',
       'Golagokarnath', 'Hamirpur', 'Kurara', 'Ruperdeeha', 'Saidpur',
       'Shahaswan', 'Visoli', 'Wazirganj', 'Badda', 'Barhaj',
       'Maharajganj', 'Mau', 'Muskara', 'Richha', 'Milak', 'Sindholi'],
       'West_Bengal': ['Alipurduar', 'Balurghat', 'Bankura Sadar', 'Barasat',
       'Baruipur(Canning)', 'Belacoba', 'Beldanga', 'Bethuadahari',
       'Birbhum', 'Bishnupur(Bankura)', 'Bolpur', 'Burdwan',
       'Champadanga', 'Coochbehar', 'Dinhata', 'Durgapur', 'Egra/contai',
       'English Bazar', 'Ghatal', 'Guskara', 'Habra', 'Haldibari',
       'Indus', 'Islampur', 'Jalpaiguri Sadar', 'Jangipur', 'Jhargram',
       'Kaliaganj', 'Kalimpong', 'Kalipur(Champadanga)', 'Kalna',
       'Kalyani', 'Karimpur', 'Kasimbazar', 'Katwa', 'Khatra', 'Lalbagh',
       'Mathabhanga', 'Medinipur(West)', 'Memari', 'Midnapore Sadar',
       'Nadia', 'Pandua', 'Pundibari', 'Purulia', 'Raiganj(Kalinganj)',
       'Ramkrishanpur(Howrah)', 'Rampurhat', 'Sainthia(Suri)', 'Samsi',
       'Tamluk (Medinipur E)', 'Toofanganj', 'Asansol', 'Baxirhat',
       'Chakdah', 'Darjeeling(Klimpong)', 'Diamond Harbour',
       'Falakata(Dhupguri)', 'Gajol', 'Gangarampur', 'Howrah',
       'Jiaganj(Lalbagh)', 'Kandi', 'Kolaghat', 'Mekhliganj',
       'Sealdah Koley Market', 'Sheoraphuly', 'Balarampur', 'Bishnupur',
       'ChinSurah', 'Darjeeling', 'Diamond Harbour(South 24-pgs)',
       'Falakata', 'Garbeta(Medinipur)', 'Guskara(Burdwan)',
       'Indus(Bankura Sadar)', 'Jiaganj', 'Kalipur',
       'Karsiyang(Matigara)', 'Kasipur', 'Raiganj', 'Ranaghat',
       'Ranaghat(Kalyani)', 'Sainthia', 'Siliguri', 'Uluberia',
       'Gangarampur(Dakshin Dinajpur)']}

bajra_district_dict = {'Delhi': ['Delhi'],
       'Haryana':['Hissar', 'Ambala', 'Mahendragarh-Narnaul', 'Jhajar', 'Faridabad',
       'Panchkula', 'Bhiwani', 'Fatehabad', 'Kaithal', 'Sirsa', 'Gurgaon',
       'Sonipat', 'Palwal', 'Mewat', 'Panipat', 'Jind', 'Rewari',
       'Karnal', 'Kurukshetra', 'Rohtak', 'Yamuna Nagar'],
       'Madhya_Pradesh': ['Ratlam', 'Shajapur', 'Panna', 'Bhind', 'Alirajpur', 'Morena',
       'Badwani', 'Guna', 'Ashoknagar', 'Sehore', 'Shivpuri', 'Ujjain',
       'Dhar', 'Khargone', 'Rewa', 'Balaghat', 'Raisen', 'Betul', 'Datia',
       'Mandsaur', 'Bhopal', 'Rajgarh', 'Mandla', 'Sagar', 'Burhanpur',
       'Chhindwara', 'Gwalior', 'Dewas', 'Dindori', 'Narsinghpur',
       'Harda', 'Khandwa', 'Indore', 'Jabalpur', 'Neemuch', 'Jhabua',
       'Katni', 'Seoni', 'Chhatarpur', 'Satna', 'Shehdol', 'Sheopur',
       'Sidhi', 'Umariya'], 
       'Maharashtra': ['Yavatmal', 'Sangli', 'Amarawati', 'Ahmednagar', 'Latur',
       'Hingoli', 'Sholapur', 'Akola', 'Raigad', 'Jalgaon', 'Jalana',
       'Beed', 'Gondiya', 'Wardha', 'Aurangabad', 'Pune', 'Nanded',
       'Buldhana', 'Gadchiroli', 'Chandrapur', 'Nashik', 'Satara',
       'Dhule', 'Parbhani', 'Osmanabad', 'Nagpur', 'Thane', 'Vashim',
       'Kolhapur', 'Mumbai', 'Nandurbar', 'Bhandara'], 
       'Rajasthan': ['Sirohi', 'Ajmer', 'Alwar', 'Ganganagar', 'Baran', 'Jaipur',
       'Barmer', 'Dausa', 'Bharatpur', 'Hanumangarh', 'Jhalawar',
       'Jalore', 'Bhilwara', 'Bikaner', 'Jodhpur', 'Bundi', 'Jhunjunu',
       'Churu', 'Nagaur', 'Tonk', 'Dholpur', 'Chittorgarh', 'Sikar',
       'Swai Madhopur', 'Karauli', 'Kota', 'Jaisalmer', 'Pali',
       'Rajasamand', 'Udaipur'], 
       'Tamil_Nadu': ['Thirunelveli', 'Ariyalur', 'Virudhunagar', 'Cuddalore', 'Theni',
       'Thiruvannamalai', 'Coimbatore', 'Dharmapuri', 'Erode', 'Dindigul',
       'Salem', 'Vellore', 'Thiruchirappalli',
       'Nagercoil (Kannyiakumari)', 'Namakkal', 'Thiruvarur',
       'Villupuram', 'Tuticorin'], 
       'Telangana': ['Mahbubnagar', 'Nizamabad', 'Nalgonda', 'Warangal', 'Medak',
       'Hyderabad', 'Khammam', 'Ranga Reddy', 'Karimnagar'], 
       'Uttar_Pradesh':['Auraiya', 'Agra', 'Allahabad', 'Etah', 'Aligarh',
       'Jyotiba Phule Nagar', 'Bulandshahar', 'Bareilly', 'Banda',
       'Badaun', 'Unnao', 'Lucknow', 'Basti', 'Mainpuri', 'Etawah',
       'Hamirpur', 'Kaushambi', 'Muradabad', 'Fatehpur', 'Farukhabad',
       'Kannuj', 'Kanpur', 'Saharanpur', 'Gautam Budh Nagar',
       'Mau(Maunathbhanjan)', 'Firozabad', 'Ghaziabad',
       'Bhadohi(Sant Ravi Nagar)', 'Hathras', 'Hardoi', 'Sitapur',
       'Jalaun (Orai)', 'Ghazipur', 'Chitrakut', 'Shahjahanpur',
       'Muzaffarnagar', 'Mathura', 'Mahoba', 'Meerut', 'Siddharth Nagar',
       'Gonda', 'Balrampur', 'Sultanpur', 'Rampur', 'Varanasi']}

bajra_market_dict = {'Delhi': ['Najafgarh', 'Narela', 'Shahdara'],
       'Haryana':['Adampur', 'Ambala Cantt.', 'Ambala City', 'Ateli', 'Bahadurgarh',
       'Ballabhgarh', 'Barwala', 'Barwala(Hisar)', 'Behal', 'Beri',
       'Bhattu Kalan', 'Bhiwani', 'Bhuna', 'Ch. Dadri', 'Dhand', 'Ding',
       'Ellanabad', 'Farukh Nagar', 'Fatehabad', 'Gohana', 'Gurgaon',
       'Hansi', 'Hassanpur', 'Hathin', 'Hissar', 'Hodal', 'Israna',
       'Jakhal', 'Jhajjar', 'Jind', 'Jui', 'Jullana', 'kalanwali',
       'Kalawali(Odhan)', 'Kalayat', 'Khanina', 'Kosli', 'Kunjpura',
       'Ladwa', 'Loharu', 'Loharu(Dighwa)', 'Madlauda', 'Meham',
       'Mohindergarh', 'Naraingarh', 'Narnaud(Bass)', 'Narnaul',
       'Narnaund', 'Narwana', 'New Grain Market , Bhiwani',
       'New Grain Market , Faridabad', 'New Grain Market , Jind',
       'New Grain Market , Rohtak', 'New Grain Market , Sonipat',
       'Nilokheri', 'Nuh', 'Pai', 'Palwal', 'Panchkula', 'Pataudi',
       'Pillukhera', 'Pundri', 'Punhana', 'Raipur Rai', 'Rania', 'Ratia',
       'Rattia', 'Rerozepur Zhirka', 'Rewari', 'Rohtak', 'Sadhaura',
       'Safidon', 'Samalkha', 'Sampla', 'Shahabad', 'Shahzadpur', 'Sirsa',
       'Siwani', 'Sohna', 'Sonepat', 'Sonepat(Kharkhoda)', 'Taura',
       'Tohana', 'Tosham', 'Uchana', 'Uklana', 'Yamuna Nagar'], 
      'Madhya_Pradesh': ['A lot', 'Agar', 'Ajaygarh', 'Akodia', 'Alampur', 'Alirajpur',
       'Ambaha', 'Anjad', 'Aron', 'Ashoknagar', 'Ashta', 'Badarwas',
       'Badnagar', 'Badnawar', 'Badnawar(F&V)', 'Badod', 'Badwaha',
       'Badwani', 'Baikunthpur', 'Balaghat', 'Balwadi', 'Barad', 'Bareli',
       'Betul', 'Bhander', 'Bhanpura', 'Bhikangaon', 'Bhind', 'Bhopal',
       'Biaora', 'Bichhiya', 'Bina', 'Binaganj', 'Burhanpur', 'Chaakghat',
       'Chaurai', 'Chhapiheda', 'Chhindwara', 'Dabra', 'Datia',
       'Devandranagar', 'Dewas', 'Dhamnod', 'Dhar', 'Dindori',
       'Gadarwada', 'Gohad', 'Gorakhpur', 'Gotegaon', 'Guna',
       'Haatpipliya', 'Harda', 'Harsood', 'Ichhawar', 'Indore(F&V)',
       'Jabalpur', 'Jaora', 'Javad', 'Jhabua', 'Jobat', 'Jora',
       'Kailaras', 'Kalapipal', 'Kannod', 'Kareli', 'Karera', 'Karhi',
       'Kasrawad', 'Katangi', 'Katni', 'Keolari', 'Kesli', 'Khachrod',
       'Khandwa', 'Khaniadhana', 'Khargone', 'Khategaon', 'Khetia',
       'Kolaras', 'Kukshi', 'Kumbhraj', 'Kurawar', 'Lahar', 'Lashkar',
       'Loharda', 'Magroni', 'Mahidpur', 'Maksudangarh', 'Manasa',
       'Manawar', 'Mandla', 'Mandsaur', 'Mehgaon', 'Mhow',
       'Momanbadodiya', 'Morena', 'Mow', 'Mungawali', 'Nalkehda',
       'Narsinghpur', 'Naugaon', 'Neemuch', 'Pandhana', 'Pandhurna',
       'Petlawad', 'Pichhour', 'Piplya', 'Pohari', 'Porsa', 'Raghogarh',
       'Rajgarh', 'Rajnagar', 'Ratlam', 'Sabalgarh', 'Sailana', 'Sajapur',
       'Sanawad', 'Sanwer', 'Satna', 'Saunsar', 'Segaon', 'Sehora',
       'Sendhwa', 'Seoni', 'Sevda', 'Shahdol', 'Shahpura(Jabalpur)',
       'Shajapur', 'Shamgarh', 'Sheopurbadod', 'Sheopurkalan', 'Shivpuri',
       'Shujalpur', 'Sidhi', 'Sonkatch', 'Susner', 'Suvasra', 'Taal',
       'Tarana', 'Thandla', 'Ujjain', 'Umariya', 'Unhel', 'Varaseoni',
       'Vijaypur'],
       'Maharashtra': ['Aarni', 'Aatpadi', 'Achalpur', 'Ahmednagar', 'Ahmedpur',
       'Akhadabalapur', 'Akkalkot', 'Akluj', 'Akola', 'Akole', 'Akot',
       'Alibagh', 'Amalner', 'Amarawati', 'Ambad (Vadigodri)',
       'Ambejaogai', 'Anajngaon', 'Arjuni', 'Ashti', 'Ashti(Jalna)',
       'Aurangabad', 'Ausa', 'Balapur', 'Baramati', 'Barshi',
       'Barshi(Vairag)', 'Beed', 'Bhokar', 'Bhokardan',
       'Bhokardan(Pimpalgaon Renu)', 'Bhor', 'Bhusaval',
       'Bodwad(Varangaon)', 'Buldhana(Dhad)', 'Chalisgaon', 'Chamorshi',
       'Chandrapur', 'Chandur Railway', 'Chandvad', 'Chikali', 'Chopada',
       'Dahivadi', 'Daryapur', 'Deoulgaon Raja', 'Devala', 'Dharangaon',
       'Dharmabad', 'Dhule', 'Digras', 'Dondaicha',
       'Dondaicha(Sindhkheda)', 'Dound', 'Gandchiroli', 'Gangakhed',
       'Gangapur', 'Gevrai', 'Ghansawangi', 'Hadgaon', 'Hingoli',
       'Indapur', 'Indapur(Bhigwan)', 'Jalana', 'Jalgaon',
       'Jalgaon Jamod(Aasalgaon)', 'Jalgaon(Jamod)', 'Jalgaon(Masawat)',
       'Jalkot', 'Jalna(Badnapur)', 'Jamkhed', 'Jamner', 'Jawali',
       'Jintur', 'Kada', 'Kaij', 'Kalamb(Osmanabad)', 'Kalamnuri',
       'Kalmeshwar', 'Kalvan', 'Kalyan', 'Kandhar', 'Kannad', 'Karanja',
       'Karjat(Raigad)', 'Karjat(Rashin)', 'Karmala', 'Khamgaon',
       'Khed(Chakan)', 'Kille Dharur', 'Kolhapur', 'Kolhapur(Laxmipuri)',
       'Kopargaon', 'Koregaon', 'Kundalwadi', 'Kurdwadi',
       'Kurdwadi(Modnimb)', 'Lasalgaon', 'Lasalgaon(Niphad)',
       'Lasur Station', 'Latur', 'Loha', 'Lonand', 'Lonar', 'Majalgaon',
       'Malegaon', 'Malegaon(Umarane)', 'Malkapur', 'Mangal Wedha',
       'Mangrulpeer', 'Manmad', 'Manora', 'Mantha', 'Manwat', 'Mehekar',
       'Mohol', 'Morshi', 'Motala', 'Mumbai', 'Murim', 'Murud', 'Nanded',
       'Nandgaon', 'Nandura', 'Nandurbar', 'Navapur', 'Newasa', 'Nilanga',
       'Nira', 'Nira(Saswad)', 'Osmanabad', 'Pachora', 'Paithan',
       'Palthan', 'Palus', 'Pandharpur', 'Panvel', 'Parali Vaijyanath',
       'Parbhani', 'Parner', 'Parola', 'Partur', 'Pathardi', 'Pathari',
       'Pimpalgaon', 'Pune', 'Pune(Hadapsar)', 'Pune(Khadiki)',
       'Pune(Pimpri)', 'Purna', 'Pusad', 'Rahata', 'Rahuri',
       'Rahuri(Songaon)', 'Rahuri(Vambori)', 'Raver', 'Roha', 'Sakri',
       'Sangamner', 'Sangli', 'Sangli(Miraj)',
       'Sangli(Phale, Bhajipura Market)', 'Sangola', 'Sangrampur',
       'Sangrampur(Varvatbakal)', 'Satana', 'Satara', 'Savali', 'Selu',
       'Shahada', 'Shegaon', 'Shevgaon', 'Shevgaon(Bodhegaon)', 'Shirpur',
       'Shirur', 'Shrigonda', 'Shrirampur', 'Shrirampur(Belapur)',
       'Sillod', 'Sillod(Bharadi)', 'Sindkhed Raja', 'Sinner', 'Solapur',
       'Sonpeth', 'Taloda', 'Tasgaon', 'Telhara', 'Tuljapur', 'Udgir',
       'Ulhasnagar', 'Umarga', 'Vaduj', 'Vai', 'Vaijpur', 'Varud',
       'Varud(Rajura Bazar)', 'Vasai', 'Washim', 'Yeola', 'Yeotmal',
       'Chakur', 'Dindori', 'Dudhani', 'Indapur(Nimgaon Ketki)',
       'Jintur(Bori)', 'Kada(Ashti)', 'Lohara', 'Mulshi',
       'Pachora(Bhadgaon)', 'Paranda', 'Vadvani', 'Yawal', 'Akkalkuwa',
       'Fruit Market', 'Lakhani', 'Nagpur', 'Rajura', 'Suragana',
       'Umared'],
       'Rajasthan': ['Abu Road', 'Ajmer (Grain)', 'Alwar', 'Anoopgarh', 'Anta', 'Bagru',
       'Balotra', 'Bandikui', 'Baran', 'Barmer', 'Bayana', 'Beawar',
       'Bhadara', 'Bharatpur', 'Bharatpur(Kumer)',
       'Bhawani Mandi(Raipur)', 'Bheenmal(Ranlwada)', 'Bhilwara',
       'Bhinmal', 'Bijay Nagar', 'Bikaner (Grain)', 'Bilara', 'Bundi',
       'Chaksu', 'Chirwa', 'Chomu', 'Churu', 'Dausa', 'Deedwana',
       'Deedwana(Choti Khatu)', 'Deeg', 'Degana', 'DEI(Bundi)', 'Deoli',
       'Dholpur', 'Fatehnagar', 'Fatehpur', 'Gajsinghpur',
       'Gangapur City', 'Gangapurcity(Old Lal mandi)', 'Gharsana',
       'Goluwala', 'Hanumangarh', 'Hanumangarh Town', 'Hindoun', 'Itawa',
       'Jaipur (Grain)', 'Jaipur(Bassi)', 'Jaipur(Grain)(Chandpole)',
       'Jaipur(Grain)(Sodala)', 'Jaisalmer', 'Jaitaran', 'Jaitsar',
       'Jalore', 'Jhunjhunu', 'Jodhpur (Grain)(Mandor)',
       'Jodhpur(Grain)(Bhagat Ki Kothi)', 'Jodhpur(Grain)(Phalodi)',
       'Kama', 'Kekri', 'Kesarisinghpur', 'Keshoraipatan', 'Khairthal',
       'Khajuwala', 'Kherli', 'Kishan Renwal(Fulera)',
       'Kishan Renwal(Sambhar)', 'Kishangarh Renwal', 'Kota', 'Kotputli',
       'Kotputli(Pawla)', 'Kuchaman City', 'Lalgarh Jatan', 'Lalsot',
       'Lalsot(Mandabari)', 'Lunkaransar', 'Madanganj Kishanganj',
       'Mahuwa Mandawar', 'Malpura', 'Malpura(Todaraisingh)',
       'Mandalgarh', 'Merta City', 'Nadwai', 'Nagar', 'Nagaur',
       'Nagaur(Jayal)', 'Nawalgarh', 'Neem Ka Thana', 'Nimbahera',
       'Niwai', 'Nohar', 'Nokha', 'Padampur', 'Pali', 'Pilli Banga',
       'Pipar City', 'Raisingh Nagar', 'Rajasamand', 'Ramaganj Mandi',
       'Ramgang Mandi(Bapawarkala)', 'Rani', 'Rawatsar', 'Rawla',
       'Sadulpur(ph 3)', 'Sadulshahar', 'Sanchor', 'Sangriya',
       'Sardar Shahar', 'Sawai Madhopur', 'Sikar', 'Sojat Road',
       'Sri Karanpur', 'Sri Madhopur', 'Sri Vijayanagar', 'Sridungargarh',
       'Sriganganagar', 'Sujangarh(Churu)', 'Sumerganj', 'Sumerpur',
       'Surajgarh', 'Suratgarh', 'Tonk', 'Udaipur', 'Uniyara',
       'Vijay Nagar(Gulabpura)', 'Alwar(FV)', 'Atru',
       'Bandikui(Geejgarh)', 'Bhawani Mandi', 'Khedh(Bodaramev)',
       'Khedli(laxmangarh)', 'Mahua Mandabar(Mahua)', 'Mathania',
       'Sadulpur'],
       'Tamil_Nadu': ['Ambasamudram', 'Ariyalur Market', 'Aruppukottai', 'Bhuvanagiri',
       'Bodinayakkanur', 'Chethupattu', 'Coimbatore', 'Cuddalore',
       'Dharampuri', 'Dharapuram', 'Dindigul', 'Erode', 'Gangavalli',
       'Karamadai', 'Katpadi', 'Kurinchipadi', 'Manapparai',
       'Monday Market', 'Namakkal', 'Rajapalayam', 'Rasipuram', 'Salem',
       'Sankarankovil', 'Sathur', 'Sethiathoppu', 'Shrimushnam',
       'Thammampati', 'Theni', 'Thiruppur', 'Thiruvannamalai',
       'Thiruvarur', 'Thondamuthur', 'Thuraiyur', 'Tindivanam',
       'Tittakudi', 'Udumalpet', 'Ulundurpettai', 'Vellore',
       'Vilathikulam', 'Virudhachalam', 'Virudhunagar'], 
       'Telangana': ['Achampet', 'Achampet(Amrabad)', 'Alampur', 'Amangal', 'Armoor',
       'Badepalli', 'Bodhan', 'Devarakonda', 'Excise Colony,RBZ',
       'Gadwal', 'Gadwal(Lezza)', 'Gajwel', 'Halia', 'Hyderabad (F&V)',
       'Kammarpally', 'Kodad', 'Kothagudem', 'Mahbubnagar(Nawabpet)',
       'Medak', 'Medchal', 'Metpally', 'Miryalaguda', 'Nagarkurnool',
       'Nagur', 'Nalgonda', 'Narsapur', 'Neredcherla', 'NGOs Colony,RBZ',
       'Nizamabad', 'Pullanga X Road,RBZ', 'Ramakrisnapuram,RBZ',
       'Ramayampet', 'Sadasivpet(Sangareddy)', 'Siddipet', 'Suryapeta',
       'Togguta', 'Vanasthalipuram,RBZ', 'Vemulawada', 'Vikarabad',
       'Wanaparthy town', 'Warangal', 'Weekly Market Area,RBZ',
       'Zaheerabad'], 
       'Uttar_Pradesh':['Achalda', 'Achnera', 'Agra', 'Ajuha', 'Aliganj', 'Aligarh',
       'Allahabad', 'Amroha', 'Anoop Shahar', 'Anwala', 'Atarra',
       'Atrauli', 'Auraiya', 'Awagarh', 'Baberu', 'Badayoun', 'Banda',
       'Bangarmau', 'Banthara', 'Bareilly', 'Basti', 'Bewar', 'Bharthna',
       'Bharuasumerpur', 'Bharwari', 'Bhehjoi', 'Bilsi', 'Bindki',
       'Buland Shahr', 'Chandausi', 'Charra', 'Chhibramau',
       'Chhibramau(Kannuj)', 'Choubepur', 'Chutmalpur', 'Dadri',
       'Dankaur', 'Dataganj', 'Devband', 'Dibiapur', 'Divai',
       'Doharighat', 'Etah', 'Etawah', 'Farukhabad', 'Fatehabad',
       'Fatehpur Sikri', 'Firozabad', 'Ganjdudwara', 'Ghaziabad',
       'Ghiraur', 'Gopiganj', 'Haathras', 'Hapur', 'Hardoi',
       'Hargaon (Laharpur)', 'Hasanpur', 'Jagnair', 'Jahanabad',
       'Jahangirabad', 'Jalaun', 'Jangipura', 'Jarar', 'Jasra',
       'Jasvantnagar', 'Javer', 'Jhijhank', 'Kalpi', 'Kamlaganj',
       'Kanpur(Grain)', 'Karvi', 'Kasganj', 'Katra', 'Kayamganj', 'Khaga',
       'Khair', 'Khairagarh', 'Khatauli', 'Khurja', 'Kishunpur',
       'Kosikalan', 'Kurara', 'Lucknow', 'Madhoganj', 'Madhogarh',
       'Mahoba', 'Mainpuri', 'Mathura', 'Mau(Chitrakut)', 'Meerut',
       'Mohamadabad', 'Naugarh', 'Nawabganj', 'Panchpedwa', 'Pukhrayan',
       'Rura', 'Sambhal', 'Samsabad', 'Sandi', 'Sandila', 'Shadabad',
       'Shahaswan', 'Shahjahanpur', 'Shikohabad', 'Sikanderabad',
       'Sikandraraau', 'Sikarpur', 'Sindholi', 'Sirsa', 'Sirsaganj',
       'Siyana', 'Sultanpur', 'Tanda(Rampur)', 'Tulsipur', 'Tundla',
       'Ujhani', 'Uttaripura', 'Varanasi(Grain)', 'Varipaal', 'Visoli',
       'Viswan', 'Wazirganj', 'Yusufpur']}